##########################################################################################################
#Codes for "Mortality risk and burden associated with all criteria air pollutants in China: Causal machine-learning evidence"
#Authors for codes: Huimeng Liu, Jian Lei, Yunxing Jiang, Lijun Bai, et.al.
#Correspondence to Shaowei Wu, Yuewei Liu.
###########################################################################################################

##########################################################################################################
# Notes on required inputs and expected outputs
#
# This script aggregates DAILY attributable numbers (AN) into AN sums by year, then converts them into
# ANNUAL attributable fractions (AF%) using annual total death counts as denominators. It does not re-fit
# any exposure–response model. It is a pure post-processing / aggregation step.
#
# ------------------------------
# 1) REQUIRED INPUT DATA (FROM UPSTREAM SCRIPTS)
# ------------------------------
# The script expects OUT_DIR to already contain two daily output files generated by the upstream
# "daily attributable fractions / numbers" script:
#
# (A) attributable_number_daily_all_pollutants.csv
#     - Must contain:
#         * Date: daily date (YYYY-MM-DD)
#         * For each pollutant p in POLLUTANTS:
#             p        : daily attributable number (AN_mid)
#             p_LCL    : daily AN lower CI endpoint (AN_lo)
#             p_UCL    : daily AN upper CI endpoint (AN_hi)
#     - Example required columns for PM25:
#         Date, PM25, PM25_LCL, PM25_UCL
#
# (B) daily_death_number.csv
#     - Must contain:
#         * Date: daily date (YYYY-MM-DD)
#         * N   : observed daily death count for the selected ICD outcome group (baseline deaths)
#
# IMPORTANT:
# - The daily death counts N must correspond exactly to the same outcome definition (ICD selection)
#   used when generating the daily AN/AF outputs. Otherwise, annual AF% will be inconsistent.
# - Dates in both files should cover the same study period and be aligned at daily resolution.
#
# ------------------------------
# 2) KEY PARAMETERS
# ------------------------------
# - OUT_DIR: directory that stores upstream daily outputs and where this script will write annual output.
# - POLLUTANTS_BASE / INCLUDE_SO2 / INCLUDE_CO:
#     controls which pollutants will be aggregated.
#     The pollutant names must match the column names in attributable_number_daily_all_pollutants.csv.
#
# ------------------------------
# 3) OUTPUTS
# ------------------------------
# The script writes one CSV to OUT_DIR:
#
# (1) annual_AF_all_pollutants.csv
#     - A wide table with rows:
#         year = "2013", "2014", ..., "2019", and a final "Total" row
#     - For each pollutant p in POLLUTANTS, three columns are produced:
#         p        : annual attributable fraction AF_mid (%) for that year
#         p_LCL    : annual AF lower CI endpoint (%)
#         p_UCL    : annual AF upper CI endpoint (%)
#     - Annual AF% is computed as:
#         AF_year(%) = ( sum_over_days_in_year AN_day ) / ( sum_over_days_in_year deaths_day ) * 100
#     - The "Total" row sums AN across all years and divides by total deaths across all years.
#
# ------------------------------
# 4) COMMON PITFALLS / VALIDATION CHECKS
# ------------------------------
# - Missing pollutant columns:
#     If the daily AN file does not contain p / p_LCL / p_UCL for some pollutant p, that pollutant
#     will be skipped with a warning.
# - Denominator mismatch:
#     If daily deaths (N) are from a different ICD outcome group than the AN file, annual AF% will be wrong.
# - Zero deaths:
#     If annual deaths are 0 for a given year, AF% is set to NA for that year.
###########################################################################################################
rm(list = ls())
options(stringsAsFactors = FALSE)

suppressPackageStartupMessages({
  library(data.table)
  library(lubridate)
})

# ---- Configuration (HIDDEN PATH) ----
OUT_DIR <- "PATH/TO/OUTPUT_DIR"

# ---- Switches: include additional pollutants ----
INCLUDE_SO2 <- TRUE
INCLUDE_CO  <- TRUE

# Base pollutants (consistent with upstream scripts)
POLLUTANTS_BASE <- c("PM25","PM2510","O3","NO2")

# Final pollutant list for aggregation
POLLUTANTS <- POLLUTANTS_BASE
if (INCLUDE_SO2) POLLUTANTS <- c(POLLUTANTS, "SO2")
if (INCLUDE_CO)  POLLUTANTS <- c(POLLUTANTS, "CO")

# ---- Read daily outputs ----
# Daily attributable numbers (AN) with CI columns
an_daily <- fread(file.path(OUT_DIR, "attributable_number_daily_all_pollutants.csv"))
stopifnot("Date" %in% names(an_daily))
an_daily[, Date := as.Date(Date)]
an_daily[, year := year(Date)]

# Daily death counts for the selected ICD outcome
deaths_daily <- fread(file.path(OUT_DIR, "daily_death_number.csv"))
stopifnot(all(c("Date","N") %in% names(deaths_daily)))
deaths_daily[, Date := as.Date(Date)]
deaths_daily[, year := year(Date)]

# ---- Annual denominators (deaths) ----
deaths_yearly <- deaths_daily[, .(deaths = sum(N, na.rm = TRUE)), by = year][order(year)]
deaths_total  <- sum(deaths_yearly$deaths, na.rm = TRUE)

# ---- Utility: annual AF% (and CI) from annual AN sums ----
calc_annual_AF_for_pollutant <- function(p) {
  need <- c(p, paste0(p, "_LCL"), paste0(p, "_UCL"))
  if (!all(need %in% names(an_daily))) {
    warning(sprintf("Missing columns in daily AN file for %s: %s (skipping).",
                    p, paste(setdiff(need, names(an_daily)), collapse = ", ")))
    return(NULL)
  }
  
  # Annual AN sums (mid / LCL / UCL)
  an_yearly <- an_daily[, .(
    AN_mid = sum(get(p),                na.rm = TRUE),
    AN_lo  = sum(get(paste0(p,"_LCL")), na.rm = TRUE),
    AN_hi  = sum(get(paste0(p,"_UCL")), na.rm = TRUE)
  ), by = year][order(year)]
  
  # Merge with annual deaths and compute annual AF (%)
  tmp <- merge(an_yearly, deaths_yearly, by = "year", all.x = TRUE)
  AF_mid <- ifelse(tmp$deaths > 0, tmp$AN_mid / tmp$deaths * 100, NA_real_)
  AF_lo  <- ifelse(tmp$deaths > 0, tmp$AN_lo  / tmp$deaths * 100, NA_real_)
  AF_hi  <- ifelse(tmp$deaths > 0, tmp$AN_hi  / tmp$deaths * 100, NA_real_)
  
  # Total row (sum across years)
  an_tot_mid <- sum(an_yearly$AN_mid, na.rm = TRUE)
  an_tot_lo  <- sum(an_yearly$AN_lo,  na.rm = TRUE)
  an_tot_hi  <- sum(an_yearly$AN_hi,  na.rm = TRUE)
  
  AF_mid_tot <- ifelse(deaths_total > 0, an_tot_mid / deaths_total * 100, NA_real_)
  AF_lo_tot  <- ifelse(deaths_total > 0, an_tot_lo  / deaths_total * 100, NA_real_)
  AF_hi_tot  <- ifelse(deaths_total > 0, an_tot_hi  / deaths_total * 100, NA_real_)
  
  out <- data.table(
    year       = c(as.character(tmp$year), "Total"),
    AF_mid_col = c(AF_mid, AF_mid_tot),
    AF_lo_col  = c(AF_lo,  AF_lo_tot),
    AF_hi_col  = c(AF_hi,  AF_hi_tot)
  )
  setnames(out,
           c("AF_mid_col","AF_lo_col","AF_hi_col"),
           c(p, paste0(p,"_LCL"), paste0(p,"_UCL")))
  out
}

# ---- Main: build a single wide table for all pollutants ----
years_vec <- sort(unique(deaths_yearly$year))
annual_AF_all <- data.table(year = c(as.character(years_vec), "Total"))

for (p in POLLUTANTS) {
  res_p <- calc_annual_AF_for_pollutant(p)
  if (is.null(res_p)) next
  annual_AF_all <- merge(annual_AF_all, res_p, by = "year", all.x = TRUE, sort = FALSE)
}

# ---- Export ----
out_file <- file.path(OUT_DIR, "annual_AF_all_pollutants.csv")
fwrite(annual_AF_all, out_file)
cat("Done. Annual AF% (with CI) saved to: ", out_file, "\n")
